name: VMServers
version: 1.0.0
api: [3.0.0-ALPHA12, 3.0.0-ALPHA13]
main: Servers\Main
author: Zeao
description: Allows to transfer between servers using a simple command.
commands:
    servers:
        description: Allows you to see a list of servers you can teleport to.
    server:
        description: Choose between servers through out The Void Network.